project:
  type: website
  output-dir: docs

website:
  title: "Yusuf Khalil -  CPLN 5920 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: labs/lab_0/lab_0.html
            text: "Lab 0: dplyr Basics"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
